/* eslint-disable import/prefer-default-export */
export const AT = {
  FETCH_CATALOG_PENDING: 'FETCH_CATALOG_PENDING',
  FETCH_CATALOG_SUCCESS: 'FETCH_CATALOG_SUCCESS',
  FETCH_CATALOG_ERROR: 'FETCH_CATALOG_ERROR',
  ADD_PRESTATION: 'ADD_PRESTATION',
  DELETE_PRESTATION: 'DELETE_PRESTATION',
  ADD_ADDRESS: 'ADD_ADDRESS',
  ADD_APPOINTMENT: 'ADD_APPOINTMENT',
  BOOKING_PENDING: 'BOOKING_PENDING',
  BOOKING_SUCCESS: 'BOOKING_SUCESS',
  BOOKING_ERROR: 'BOOKING_ERROR',
  INCREASE_QTY: 'INCREASE_QTY',
  DECREASE_QTY: 'DECREASE_QTY',
};
