/* eslint-disable import/prefer-default-export */
export const AT = {
  FETCH_CATALOG_PENDING: 'FETCH_CATALOG_PENDING',
  FETCH_CATALOG_SUCCESS: 'FETCH_CATALOG_SUCCESS',
  FETCH_CATALOG_ERROR: 'FETCH_CATALOG_ERROR',
  ADD_PRESTATION: 'ADD_PRESTATION',
  DELETE_PRESTATION: 'DELETE_PRESTATION',
  ADD_ADRESS: 'ADD_ADRESS',
  ADD_APPOINTMENT: 'ADD_APPOINTMENT',
  BOOKING_SUCCES: 'BOOKING_SUCESS',
  BOOKING_ERROR: 'BOOKING_ERROR',
};
